In [1]:
import numpy as np

list_data=[1, 2, 3]
array=np.array(list_data)

print(array)
print(len(list_data))
print(array.size)
print(array.dtype)
print(array[2])

[1 2 3]
3
3
int32
3


In [2]:
#0부터 3까지의 배열 만들기
array1=np.arange(4)
print(array1)

[0 1 2 3]


In [3]:
#4, 4인 이차원 배열 0으로 초기화
array2=np.zeros((4,4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#3, 3인 이차원 배열 1로 초기화
array3=np.ones((3, 3), dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [7]:
#0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4=np.random.randint(0, 10, (3, 3))
print(array4)

[[7 1 6]
 [7 8 0]
 [6 7 2]]


In [13]:
#평균이 0이고 표준편차가 1인 표준 정규분포를 띄는 배열
array5=np.random.normal(0, 1, (3, 3))
print(array5)

[[ 1.24810743  1.34838364  2.95248106]
 [-0.48803563 -0.73044777  2.0890226 ]
 [-0.40327999  0.67204733 -0.54279456]]


In [14]:
array1=np.array([1, 2, 3])
array2=np.array([4, 5, 6])
array3=np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [15]:
array1=np.array([1, 2, 3, 4])
array2=array1.reshape((2, 2))

print(array2)
print(array2.shape)

[[1 2]
 [3 4]]
(2, 2)


In [17]:
array1=np.arange(4).reshape(1, 4)
array2=np.arange(8).reshape(2, 4)

print(array1)
print(array2)

array3=np.concatenate([array1, array2], axis=0)

print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [32]:
array=np.arange(12).reshape(3, 4)
left, right=np.split(array, [2], axis=1) #axis=1로 되어있으면 [2]라는 값을 열로 인식. 배열안의 배열의 [2]로 생각한다는 거
print(left.shape)
print(right.shape)
print(left,"\n", right)
up, down=np.split(array, [2], axis=0) #axis=0으로 되어있으면 [2]라는 값은 행으로 인식. 그냥 평소처럼 제일 겉 배열의 [2]로 생각한다는 거
print(up.shape)
print(down.shape)
print(up, "\n", down)
print(array[1])

(3, 2)
(3, 2)
[[0 1]
 [4 5]
 [8 9]] 
 [[ 2  3]
 [ 6  7]
 [10 11]]
(2, 4)
(1, 4)
[[0 1 2 3]
 [4 5 6 7]] 
 [[ 8  9 10 11]]
[4 5 6 7]
