In [1]:
import numpy as np
import copy

array=np.arange(4)
print(array+2)
print(array*2)

ModuleNotFoundError: No module named 'numpy'

In [4]:
array1=np.arange(4).reshape(2, 2)
array2=np.arange(2)
array3=array1+array2

print(array3)

[[0 2]
 [2 4]]


In [9]:
array1=np.arange(8).reshape(2, 4)
array2=np.arange(8).reshape(2, 4)
array3=np.concatenate([array1, array2], axis=0)
print(array3)
array4=np.arange(4).reshape(4, 1)
print(array3+array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [19]:
array1=np.random.randint(0, 21, (4, 4))
array2=array1<10
array3=array1.copy() #개발메모장에 쓸 것
array3[array2]=100
print(array1, array2, array3, sep='\n') #sep 개발메모장에 쓰기

[[ 6  8 15 15]
 [14  6 12  6]
 [11 16  1 16]
 [19  6  0 15]]
[[ True  True False False]
 [False  True False  True]
 [False False  True False]
 [False  True  True False]]
[[100 100  15  15]
 [ 14 100  12 100]
 [ 11  16 100  16]
 [ 19 100 100  15]]


In [22]:
array=np.arange(1, 11).reshape(2, 5)

print("max :", np.max(array))
print("min :", np.min(array))
print("sum :", np.sum(array))
print("mean :", np.mean(array))

print(array)
print("sum :", np.sum(array, axis=0))
print("column sum :", np.sum(array, axis=1))

max : 10
min : 1
sum : 55
mean : 5.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum : [ 7  9 11 13 15]
column sum : [15 40]
