In [6]:
import numpy as np

array=np.arange(10)
np.save('saved.npy', array) #단일객체 저장

[0 1 2 3 4 5 6 7 8 9]


In [9]:
result=np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
array1=np.arange(10)
array2=np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2) #복수객체 저장

In [11]:
data=np.load('saved.npz')
result1=data['array1']
result2=data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [40]:
array=np.random.randint(1, 11, 5) #randint로 1차원 배열 생기게 할려면 그냥 정수로
print(array)
array.sort()
print(array)
print(array[::-1])

[2 1 1 6 8]
[1 1 2 6 8]
[8 6 2 1 1]


In [42]:
array=np.random.randint(1, 11, (2, 5))
print(array)
array.sort(axis=0)
print(array)

[[10  3  8  6  2]
 [ 3  6  3  1  5]]
[[ 3  3  3  1  2]
 [10  6  8  6  5]]
